---
deployment:
  tasks:
    - composer install --no-interaction --prefer-dist --optimize-autoloader
    - php artisan migrate --force
    - php artisan cache:clear
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
